# -*- coding: utf-8 -*-
"""CNN_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FkWygf8xqIlYkpE1trxhDSB042ZMLz3
"""

import torch.nn as nn

class CNNModel(nn.Module):
    def __init__(self):
        super(CNNModel, self).__init__()
        self.conv_block1 = nn.Sequential(
            nn.Conv2d(1, 6, kernel_size=5, stride=1, padding=2),
            nn.ReLU(),
        )
        self.conv_block2 = nn.Sequential(
            nn.Conv2d(6, 16, kernel_size=5, stride=1),
            nn.ReLU(),
        )
        self.conv_block3 = nn.Sequential(
            nn.Conv2d(16, 120, kernel_size=5, stride=1),
            nn.ReLU(),
        )
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.dropout = nn.Dropout(0.3)
        self.fc_layers = nn.Sequential(
            nn.Flatten(),
            nn.Linear(120, 84),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(84, 10)
        )

    def forward(self, x):
        x = self.conv_block1(x)
        x = self.pool(x)
        x = self.conv_block2(x)
        x = self.pool(x)
        x = self.conv_block3(x)
        x = self.dropout(x)
        x = self.fc_layers(x)
        return x

    def visualize(self, x):
        x = self.conv_block1(x)
        layer1 = x
        x = self.pool(x)
        x = self.conv_block2(x)
        layer2 = x
        return layer1, layer2