# -*- coding: utf-8 -*-
"""dnn_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZzs6_cg98c7sKG0RFZ43ms6Blh9PhaK
"""

import torch.nn as nn

class DNNModel(nn.Module):
    def __init__(self):
        super(DNNModel, self).__init__()
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(784, 128)
        self.fc2 = nn.Linear(128, 64)
        self.dropout = nn.Dropout(0.3)
        self.fc3 = nn.Linear(64, 10)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.flatten(x)
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def visualize(self, x):
        return None, None