# -*- coding: utf-8 -*-
"""resnet_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_94inpxZqX0SKomRSYKWC7d37Dsz1WxD
"""

import torch.nn as nn
import torchvision.models as models

class ResNetModel(nn.Module):
    def __init__(self):
        super(ResNetModel, self).__init__()
        self.model = models.resnet18(pretrained=False)
        # Modify first conv layer for 1 channel input
        self.model.conv1 = nn.Conv2d(1, 64, kernel_size=7, stride=2, padding=3, bias=False)
        # Modify the output layer for 10 classes
        self.model.fc = nn.Linear(self.model.fc.in_features, 10)

    def forward(self, x):
        return self.model(x)

    def visualize(self, x):
        x = self.model.conv1(x)
        x = self.model.bn1(x)
        x = self.model.relu(x)
        layer1 = x
        x = self.model.maxpool(x)
        x = self.model.layer1(x)
        layer2 = x
        return layer1, layer2