# -*- coding: utf-8 -*-
"""vgg_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OOYyKg4qAtqQKbHBvF_Ct8lvyMjEOtc
"""

import torch.nn as nn

class VGGModel(nn.Module):
    def __init__(self):
        super(VGGModel, self).__init__()
        self.block1 = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.block2 = nn.Sequential(
            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.block3 = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.dropout = nn.Dropout(0.3)
        self.fc_layers = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 3 * 3, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        x = self.block1(x)
        x = self.block2(x)
        x = self.block3(x)
        x = self.fc_layers(x)
        return x

    def visualize(self, x):
        x = self.block1(x)
        layer1 = x
        x = self.block2(x)
        layer2 = x
        return layer1, layer2